
# Global site variables

 title: "Edinburgh Data Science Training for Healthcare & Biosciences (Ed-DaSH)"
 description: > # this is for RSS feed
    This is a brief description of the Ed-DaSH website.
    This is another placeholder line.
    
    
# Misc

repository: https://github.com/edcarp/Ed-DaSH # https://github.com/edcarp/Ed_DaSH_website_prototyping
uoe-web: "https://www.ed.ac.uk"
# Author Settings
author: Ed-DaSH # add your name
# author-img: Ed_DaSH_blue_circle.svg # add your photo
about-author: Data driven life science skills development - equipping society for the future. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: edcarp # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: "team@carpentries.org" # add your Email address

# Workshop lessons

ws_unix_shell_lesson: https://swcarpentry.github.io/shell-novice/
ws_snakemake_lesson: https://carpentries-incubator.github.io/snakemake-novice-bioinformatics
ws_nextflow_lesson: https://carpentries-incubator.github.io/workflows-nextflow/

# Workshop repos

ws_unix_shell: https://github.com/swcarpentry/shell-novice 
ws_snakemake: https://github.com/carpentries-incubator/snakemake-novice-bioinformatics 
ws_nextflow: https://github.com/carpentries-incubator/workflows-nextflow/ 

# Workshops tables

data_sci_workflows: [    # repo & lesson URLs are interim to try & test functionality
  {instance: "#1", tool: "Snakemake", date: "2021-10-01", repo: "https://github.com/carpentries-incubator/snakemake-novice-bioinformatics", lesson: "https://carpentries-incubator.github.io/snakemake-novice-bioinformatics", registration: ""}, # added temporary surrogate full `date` because of format
  {instance: "#2", tool: "Nextflow", date: "2021-11-01", repo: "https://github.com/carpentries-incubator/workflows-nextflow/", lesson: "https://carpentries-incubator.github.io/workflows-nextflow/", registration: ""},
  {instance: "#3", tool: "Snakemake", date: "2022-02-01", repo: "https://github.com/carpentries-incubator/snakemake-novice-bioinformatics", lesson: "https://carpentries-incubator.github.io/snakemake-novice-bioinformatics", registration: ""},
  {instance: "#4", tool: "Nextflow", date: "2022-03-01", repo: "https://github.com/carpentries-incubator/workflows-nextflow/", lesson: "https://carpentries-incubator.github.io/workflows-nextflow/", registration: ""},
  {instance: "#5", tool: "Snakemake", date: "2022-05-01", repo: "https://github.com/carpentries-incubator/snakemake-novice-bioinformatics", lesson: "https://carpentries-incubator.github.io/snakemake-novice-bioinformatics", registration: ""},
  {instance: "#6", tool: "Nextflow", date: "2022-06-01", repo: "https://github.com/carpentries-incubator/workflows-nextflow/", lesson: "https://carpentries-incubator.github.io/workflows-nextflow/", registration: ""},
  {instance: "#7", tool: "Snakemake", date: "2022-09-01", repo: "https://github.com/carpentries-incubator/snakemake-novice-bioinformatics", lesson: "https://carpentries-incubator.github.io/snakemake-novice-bioinformatics", registration: ""},
  {instance: "#8", tool: "Nextflow", date: "2022-10-01", repo: "https://github.com/carpentries-incubator/workflows-nextflow/", lesson: "https://carpentries-incubator.github.io/workflows-nextflow/", registration: ""},
  {instance: "#9", tool: "Snakemake", date: "2022-11-01", repo: "https://github.com/carpentries-incubator/snakemake-novice-bioinformatics", lesson: "https://carpentries-incubator.github.io/snakemake-novice-bioinformatics", registration: ""},
  {instance: "#10", tool: "Nextflow", date: "2023-01-01", repo: "https://github.com/carpentries-incubator/workflows-nextflow/", lesson: "https://carpentries-incubator.github.io/workflows-nextflow/", registration: ""},
  {instance: "#11", tool: "TBC", date: "", repo: "", lesson: "", registration: ""}
]

statistics: [
  {instance: "#1", type: "Introductory Statistics", date: "2021-09-01", repo: "", lesson: "", registration: ""},
  {instance: "#2", type: "High-dimensional Statistics", date: "2021-10-01", repo: "", lesson: "", registration: ""},
  {instance: "#3", type: "Machine Learning", date: "2021-11-01", repo: "", lesson: "", registration: ""},
  {instance: "#4", type: "Introductory Statistics", date: "2022-02-01", repo: "", lesson: "", registration: ""},
  {instance: "#5", type: "High-dimensional Statistics", date: "2022-02-01", repo: "", lesson: "", registration: ""}, # If spanning across months, then start date
  {instance: "#6", type: "Machine Learning", date: "2022-03-01", repo: "", lesson: "", registration: ""},
  {instance: "#7", type: "Introductory Statistics", date: "2022-05-01", repo: "", lesson: "", registration: ""},
  {instance: "#8", type: "High-dimensional Statistics", date: "2022-05-01", repo: "", lesson: "", registration: ""},
  {instance: "#9", type: "Machine Learning", date: "2022-06-01", repo: "", lesson: "", registration: ""},
  {instance: "#10", type: "Introductory Statistics", date: "2022-07-01", repo: "", lesson: "", registration: ""},
  {instance: "#11", type: "High-dimensional Statistics", date: "2022-07-01", repo: "", lesson: "", registration: ""},
  {instance: "#12", type: "Machine Learning", date: "2022-08-01", repo: "", lesson: "", registration: ""},
  {instance: "#13", type: "Introductory Statistics", date: "2022-09-01", repo: "", lesson: "", registration: ""},
  {instance: "#14", type: "High-dimensional Statistics", date: "2022-09-01", repo: "", lesson: "", registration: ""},
  {instance: "#15", type: "Machine Learning", date: "2022-10-01", repo: "", lesson: "", registration: ""},
  {instance: "#16", type: "Introductory Statistics", date: "2022-11-01", repo: "", lesson: "", registration: ""},
  {instance: "#17", type: "High-dimensional Statistics", date: "2023-01-01", repo: "", lesson: "", registration: ""},
  {instance: "#18", type: "Machine Learning", date: "2023-02-01", repo: "", lesson: "", registration: ""}
]

fair_data_management: [
  {instance: "#1", type: "FAIR in Practice", date: "2021-10-01", repo: "", lesson: "", registration: ""},
  {instance: "#2", type: "FAIR for Leaders", date: "2021-11-01", repo: "", lesson: "", registration: ""},
  {instance: "#3", type: "FAIR in Practice", date: "2022-02-01", repo: "", lesson: "", registration: ""},
  {instance: "#4", type: "FAIR for Leaders", date: "2022-03-01", repo: "", lesson: "", registration: ""},
  {instance: "#5", type: "FAIR in Practice", date: "2022-05-01", repo: "", lesson: "", registration: ""},
  {instance: "#6", type: "FAIR for Leaders", date: "2022-06-01", repo: "", lesson: "", registration: ""},
  {instance: "#7", type: "FAIR in Practice", date: "2022-07-01", repo: "", lesson: "", registration: ""},
  {instance: "#8", type: "FAIR for Leaders", date: "2022-09-01", repo: "", lesson: "", registration: ""},
  {instance: "#9", type: "FAIR in Practice", date: "2022-10-01", repo: "", lesson: "", registration: ""},
  {instance: "#10", type: "FAIR for Leaders", date: "2022-11-01", repo: "", lesson: "", registration: ""},
  {instance: "#11", type: "FAIR in Practice", date: "2023-01-01", repo: "", lesson: "", registration: ""},
  {instance: "#12", type: "FAIR for Leaders", date: "2023-02-01", repo: "", lesson: "", registration: ""}
]




# Ed(-)DaSH Team members - for now some members are manually added

co_investigators:  [
    {name: "Alison Meynert", role: "Senior Research Fellow & IGC Bioinformatics Analysis Core Manager", affiliate: "MRC Human Genetics Unit", social_handler: "@ameynert"},
    {name: "Alex Twyford", role: "Lecturer in Botany & Academic Lead to Edinburgh Genomics", affiliate: "SBS", social_handler: ""},
    {name: "Catalina Vallejos", role: "Chancellor’s Fellow & Fellow of the Turing Institute", affiliate: "MRC Human Genetics Unit", social_handler: "@catavallejos"},
    {name: "Edward Wallace", role: "Sir Henry Dale Fellow", affiliate: "SBS", social_handler: "@ewallace"}
]
edcarp_coordination:  [
    {name: "Giacomo Peru", role: "Programme Coordinator", affiliate: "EPCC", social_handler: "@gperu"},
    {name: "Flic Anderson", role: "Development Assistant", affiliate: "SBS", social_handler: ""}
]

dev_computational_workflows:  [
    {name: "Alison Meynert", role: "Lead", affiliate: "MRC Human Genetics Unit, IGMM Bioinformatics Analysis Core Manager", curriculum: "Snakemake & Nextflow curricula", social_handler: "@ameynert"},
    {name: "Alex Twyford", role: "Lead", affiliate: "", curriculum: "", social_handler: ""},
    {name: "Tim Booth", role: "", affiliate: "Edinburgh Genomics", curriculum: "Snakemake curriculum", social_handler: "@tbooth"},
    {name: "Nathan Medd", role: "", affiliate: "Edinburgh Genomics", curriculum: "Snakemake curriculum", social_handler: ""},
    {name: "Graeme Grimes", role: "", affiliate: "MRC HGU", curriculum: "Nextflow curriulum", social_handler: "@ggrimes"},
    {name: "Flic Anderson", role: "", affiliate: "SBS", curriculum: "Nextflow curriculum", social_handler: ""}
]

dev_data_man_FAIR_principles:  [
    {name: "Edward Wallace", role: "Lead", affiliate: "", curriculum: "Data management & FAIR principles curricula", social_handler: ""},
    {name: "Andrew Millar", role: "Chair of Systems Biology & Business Owner of University Research Data Service", affiliate: "SBS", curriculum: "Data management & FAIR principles curricula", social_handler: ""},
    {name: "Andrew Romanowski", role: "SBS", affiliate: "", curriculum: "Data management & FAIR principles", social_handler: "@aromanowski"},
    {name: "Tomasz Zielinski", role: "SBS", affiliate: "", curriculum: "Data management & FAIR principles", social_handler: "@tzielins"}
]

dev_statistics:  [
    {name: "Catalina Vallejos", role: "Lead", affiliate: "MRC Human Genetics Unit", curriculum: "high dimensional statistics curriculum", social_handler: "@catavallejos"},
    {name: "Ailith Ewing", role: "Chancellor's Fellow & Joint Lead", affiliate: "MRC Human Genetics Unit and CRUK Edinburgh Centre", curriculum: "high dimensional statistics curriculum", social_handler: ""},
    {name: "Alan O'Callaghan", role: "", affiliate: "MRC Human Genetics Unit", curriculum: "high dimensional statistics curriculum", social_handler: "@Alanocallaghan"},
    {name: "Gail Robertson", role: "", affiliate: "Statistical Consultancy Unit", curriculum: "high dimensional statistics curriculum", social_handler: ""}
]

web_development:  [
    {name: "Giacomo Peru", role: "Programme Coordinator", affiliate: "EPCC", social_handler: "@gperu"},
    {name: "Flic Anderson", role: "Development Assistant", affiliate: "SBS", social_handler: ""},
    {name: "Robert Nagy", role: "Website developer", affiliate: "IGC ECRC & ECTU - Edinburgh Health Economics Group", social_handler: "@robertn01"}
]

 steering_group:  [
    {name: "Ailith Ewing", role: "Joint Statistics Lead", affiliate: "MRC Human Genetics Unit and CRUK Edinburgh Centre", curriculum: "", social_handler: ""},
    {name: "Giacomo Peru", role: "Programme Coordinator", affiliate: "EPCC", curriculum: "", social_handler: ""},
    {name: "Neil Chue Hong", role: "Director", affiliate: "the Software Sustainability Institute", curriculum: "", social_handler: "@npch"},
    {name: "Mick Watson", role: "Professor of Bioinformatics and Computational Biology", affiliate: "The Roslin Institute", curriculum: "", social_handler: ""},
    {name: "Karen Halliday", role: "Dean of Systematic Inclusion & Professor and Chair of Systems Physiology", affiliate: "The College of Science and Engineering", curriculum: "", social_handler: ""},
    {name: "Malcolm Macleod", role: "Professor of Neurology and Translational Neuroscience & UoE Academic Lead for Research Improvement and Research Integrity", affiliate: "", curriculum: "", social_handler: ""},
    {name: "Nicola Cuthbert", role: "Researcher Development Manager", affiliate: "Institute for Academic Development", curriculum: "", social_handler: ""}
]

di_funded_members:  [
    {name: "Flic Anderson", role: "", affiliate: "SBS", curriculum: "", social_handler: ""},
    {name: "Andrew Romanowski", role: "", affiliate: "SBS", curriculum: "", social_handler: ""},
    {name: "Tomasz Zielinski", role: "", affiliate: "SBS", curriculum: "", social_handler: ""},
    {name: "Tim Booth", role: "", affiliate: "Edinburgh Genomics", curriculum: "", social_handler: ""},
    {name: "Nathan Medd", role: "", affiliate: "Edinburgh Genomics", curriculum: "", social_handler: ""},
    {name: "Graeme Grimes", role: "", affiliate: "IGC", curriculum: "", social_handler: ""},
    {name: "Alan O'Callaghan", role: "", affiliate: "IGC", curriculum: "", social_handler: ""},
    {name: "Giacomo Peru", role: "", affiliate: "EPCC", curriculum: "", social_handler: ""},
    {name: "Gail Robertson", role: "", affiliate: "School of Mathematics/ SCU", curriculum: "", social_handler: ""}
]

# Web navi:

 baseurl: "/Ed_DaSH_website_prototyping/" # the subpath of your site, e.g. /blog
 url: "https://edcarp.github.io/Ed_DaSH_website_prototyping/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings

markdown: kramdown # GFM # cmark-gfm # cmark
theme: minima # Jekyll them is overwritten by HTML
future: true
show_downloads: false
google_analytics:
plugins:
  - jekyll-feed
  - jemoji
# exclude:
#  - Gemfile
#  - Gemfile.lock

# allow page redirection
plugins:
  # - jekyll-redirect-from
  
  # Where things are

collections:
    posts:
        output: true
        permalink: Ed-DaSH/:collection/:name # Ed_DaSH_website_prototyping/:collection/:name
        
# Turn on built-in syntax highlighting.

highlighter: rouge
