
# Global site variables

title: "Edinburgh Data Science Training for Healthcare & Biosciences (Ed-DaSH)"
description: > # this is for RSS feed
  This is a brief description of the Ed-DaSH website.
  This is another placeholder line.

# Workshop lessons

ws_unix_shell_lesson: https://swcarpentry.github.io/shell-novice/
ws_snakemake_lesson: https://carpentries-incubator.github.io/snakemake-novice-bioinformatics
ws_nextflow_lesson: https://carpentries-incubator.github.io/workflows-nextflow/

# Workshop repos

ws_unix_shell: https://github.com/swcarpentry/shell-novice 
ws_snakemake: https://github.com/carpentries-incubator/snakemake-novice-bioinformatics 
ws_nextflow: https://github.com/carpentries-incubator/workflows-nextflow/ 


# Web navi:

# baseurl: ""
# url: "" # if hosted from local machine/ webserver

# Social media & email

social_twitter: "@ed_dash"
social_linkedin: ""
social_facebook: ""
email: "team@carpentries.org"
github_username: "ed_dash_web"

# Build settings

markdown: kramdown
# theme: minima
future: true
show_downloads: false
google_analytics:
plugins:
  - jekyll-feed
# exclude:
#  - Gemfile
#  - Gemfile.lock

